dist: xenial

sudo: required

git:
  depth: 3

language: bash

before_install:
  - sudo apt-get install -y shellcheck

script:
  - cd $HOME && bash -c "`curl -L https://git.io/runme`"

after_script:
  - wget https://git.io/runme
  - shellcheck runme
  - vnstat
